### ISSUE TITLE
Sonar model not understood 'em2040c'

### ISSUE THREAD

**Issue by Kurtaja** [noaa-ocs-hydrography/kluster#114] opened 2024-01-05 15:28 UTC
Hi and thank you for a great application!
I've installed it on windows following this instruction, 'https://github.com/noaa-ocs-hydrography/kluster?tab=readme-ov-file#Installation'
To process I use this python snippet:
``
from HSTB.kluster.fqpr_intelligence import intel_process
from HSTB.kluster.fqpr_convenience import convert_multibeam, process_multibeam, perform_all_processing
from HSTB.kluster.fqpr_convenience import generate_new_surface
fq = perform_all_processing(r"C:\Test\0322_20210513_084312.kmall", coord_system='WGS84', vert_ref='waterline')
``
And it works fine for both .all and .kmall files collected with some random sonars. However, when I try with a file collected with a EM2040C head, the 'perform_all_processing' function give me this error ('intel_process' and 'convert_multibeam' give the same error), "NotImplementedError: Sonar model not understood "em2040c"", which appears to say that EM2040C has not been implemented. However, the README.md file contains this statement, "Kluster has been tested on:

- EK60, EK80 (Using Kluster amplitude detection, see Requirements in Documentation)
- Reson 7125, T20, T51
**- EM2040/2040c/2040p**
- EM2040 dual tx/dual rx
- EM710/712
- EM3002
- EM302/304
- EM122
- ME70 Bathy Module
", which is contradictionary to my error message. So I assume I'm doing something wrong, probably a dead simple thing, but I've not been able to point it out. Attached the requirement.txt file for the venv I've installed it on. Would you have the possibility to point me in the good direction?
[requirements.txt](https://github.com/noaa-ocs-hydrography/kluster/files/13843648/requirements.txt)
Kind regards
Kurt

**Comment by ericgyounkin** [comment] 2024-01-05 19:59
Hi Kurt,

The issue is that for the longest time, the sonar model in the .all/.kmall file for the em2040c was 'em2045'.
https://github.com/noaa-ocs-hydrography/kluster/blob/master/HSTB/kluster/xarray_conversion.py#L34

Is this a new dataset?  I'd be curious.  Adding support wouldn't be too difficult, would you be able to share a small file?

Thanks,
Eric

**Comment by Kurtaja** [comment] 2024-01-09 07:37
Thanks for the rapid reply Eric,
Sorry it took me a little while to get hold of some files I can share. Unfortunately I do not have a file small enough to upload on github, so have attached in this mail a we-transfer link, from where you can download them from instead. 
[https://we.tl/t-3ElCPWR8e0](url)
Kind regards
Kurt

**Comment by ericgyounkin** [comment] 2024-01-10 22:36
Hi Kurt, this is fixed in v1.1.6.  You should be able to reinstall and get the fix now.

**Comment by Kurtaja** [comment] 2024-01-11 08:43
Thank you very much for your prompt fix Eric. Much appreciated. 
I tried to install it in a new venv, using this instruction, 'https://github.com/noaa-ocs-hydrography/kluster?tab=readme-ov-file#Installation', and the installation did not report any errors, however, when I try to import these packages, "from HSTB.kluster.fqpr_intelligence import intel_process", I"m getting this error, "ModuleNotFoundError: No module named 'HSTB.resources'". Looking in 'site-packages\HSTB' in the venv, I have the 'drivers', 'kluster', 'shared' and 'versioning' modules, but not any resources module. Attached the requirement files for the old venv (that is working but not for EM2040C heads) and the new venv, that give me the error mentionned above, and I'm hence not able to get to work. I could not see that you have changed the import statments in your manuals. Could it be that you have forgotten to include that module in your egg? Anyhow, appreciate if you have the possibility to help me over this little bump :-).
PS: I'm running on windows 11.
[requirements_new.txt](https://github.com/noaa-ocs-hydrography/kluster/files/13900193/requirements_new.txt)
[requirements_old.txt](https://github.com/noaa-ocs-hydrography/kluster/files/13900194/requirements_old.txt)

Kind regards
Kurt

**Comment by barry-gallagher** [comment] 2024-01-11 15:50
Hi @Kurtaja 

I added the missing dependency to the setup files.  I then installed with mamba+git (instead of conda) and it appears to work for me now.  Two notes:  I use Kluster inside our standard environment Pydro so didn't notice the additional dependency, second I tried mamba since it claims to be faster and conda stuck on some standard commands for me (not Kluster related) so I may have local a configuration issue with conda so please report any more issues you see.

**Comment by barry-gallagher** [comment] 2024-01-11 18:51
As a quick follow up, I did get the conda install to work as well and will try and replace the release binary today or tomorrow.

**Comment by Kurtaja** [comment] 2024-01-12 08:15
Hi Eric and Barry, 
I confirm that this now works on EM2040C in my end too. Thank you so much for your help!
Kind regards
Kurt

**Closed** 2024-01-12 13:01 UTC
